### ISSUE TITLE
configurazione DJANGO

### ISSUE THREAD

**Issue by Simone1979** [piorio/lpc_py_manager#85]
Ciao Pablo,
dovresti aggiungere questi host per farmi provare la redirect di dominio:
bbl.lpc-ffmanagerhosting.com
lpc-ffmanagerhosting.com

nel setting.py va modificata l'entry ALLOWED_HOST aggiungendo questi 2. Il primo è per dei test, il secondo dovrebbe essere quello a regime.
dovresti avere qualcosa del genere dentro: 
ALLOWED_HOSTS=["localhost", "127.0.0.1"]
e dovrebbe diventare tipo questa
ALLOWED_HOSTS=[""localhost", "127.0.0.1","lpc-ffmanagerhosting.com","bbl.lpc-ffmanagerhosting.com"]

ciao
Sim
![screenshot_DISALLOWED_HOST](https://user-images.githubusercontent.com/91611917/135276220-eed687a5-7709-4027-bb3e-3274726c2763.jpg)
o

**Comment by piorio** [comment]
Done
