### ISSUE TITLE
Non posso aggiungere journeyman

### ISSUE THREAD

**Issue by Simone1979** [piorio/lpc_py_manager#88]
Come da descrizione. La mia squadra ha 10 giocatori + 1 morto, ricevo errore "You can't buy a journeyman if you have more than 11 players"
team Team Almighty Tivoli Reds (ATR
![Immagine 2021-10-03 175337](https://user-images.githubusercontent.com/91611917/135761871-6208da9f-4b04-477e-a7a7-7ed97258d9a4.jpg)
)

**Comment by piorio** [comment]
Buf fixed
